import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const rocker = localFont({ 
  src: './fonts/New_Rocker/NewRocker-Regular.ttf',
  variable: '--rocker'
});
const pixelFont = localFont({ 
  src: './fonts/Press_start_2P/PressStart2P-Regular.ttf',
  variable: '--pixel-font'
});

export const metadata: Metadata = {
  title: "ZEK Portfolio !?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rocker.variable} ${pixelFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
